[package]
name = "keyjutsu-desktop"
description = "The KeyJutsu desktop app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dependencies]
keyjutsu-core.workspace = true
keyjutsu-broker.workspace = true
tauri.workspace = true

[lints]
workspace = true
