// Generated by scripts/write-index.mjs from the files ts-rs writes during
// `cargo test`. Do not edit by hand; run `pnpm types:index`.
export type { StagedArtifact } from "./generated/artifacts/StagedArtifact";
