// Generated by scripts/write-index.mjs from the files ts-rs writes during
// `cargo test`. Do not edit by hand; run `pnpm types:index`.
export type { AssumptionResult } from "./generated/validation/AssumptionResult";
export type { Report } from "./generated/validation/Report";
