// Generates apps/desktop/src/tokens.css from the design kit's
// design-tokens.json, the machine-readable source of truth for KeyJutsu's
// visual design. With --check it only reports whether the file is stale, so CI
// fails if the kit changes without the CSS following it.
//
// Variable names follow the kit's own design-tokens.css (--kj-*, --bg,
// --surface-1, --text-2 and so on), with the rest of the JSON (type scale,
// control sizes, shadows, state and risk colours) added in the same style.
// The app follows the system theme unless an ancestor sets data-theme.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, "docs/brand/KeyJutsu-Design-Kit/design-tokens.json");
const target = join(root, "apps/desktop/src/tokens.css");
const t = JSON.parse(readFileSync(source, "utf8"));

// The JSON nests each value as { value, ... } or gives it directly.
const v = (x) => (x && typeof x === "object" && "value" in x ? x.value : x);
const px = (n) => (typeof v(n) === "number" && v(n) !== 0 ? `${v(n)}px` : `${v(n)}`);
const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

const lines = (entries) => entries.map(([k, val]) => `  --${k}: ${val};`);

const brand = Object.entries(t.color.brand).map(([k, x]) => {
  const name =
    {
      black: "black",
      vermilion: "red",
      vermilionHover: "red-hover",
      vermilionPressed: "red-pressed",
      vermilionTint: "red-tint",
    }[k] ?? kebab(k);
  return [`kj-${name}`, v(x)];
});
const semantic = Object.entries(t.color.semantic).map(([k, x]) => [`kj-${kebab(k)}`, v(x)]);
const state = Object.entries(t.color.state).map(([k, x]) => [`state-${kebab(k)}`, v(x)]);
const risk = Object.entries(t.risk).map(([k, x]) => [`risk-${k}`, v(x.color)]);

const type = [
  ["font-ui", v(t.typography.family.ui)],
  ["font-mono", v(t.typography.family.mono)],
  ...Object.entries(t.typography.size).map(([k, x]) => [`fs-${kebab(k)}`, px(x)]),
  ...Object.entries(t.typography.lineHeight).map(([k, x]) => [`lh-${kebab(k)}`, px(x)]),
  ...Object.entries(t.typography.weight).map(([k, x]) => [`fw-${k}`, v(x)]),
  ["tracking-caps", v(t.typography.tracking.caps)],
];
const space = Object.entries(t.spacing).map(([k, x]) => [`sp-${k}`, px(x)]);
const radius = Object.entries(t.radius).map(([k, x]) => [`r-${k}`, px(x)]);
const control = [
  ...Object.entries(t.control.height).map(([k, x]) => [`control-${k}`, px(x)]),
  ["focus-ring", v(t.control.focusRing)],
];
const layout = Object.entries(t.layout).map(([k, x]) => [`layout-${kebab(k)}`, px(x)]);
const shadow = Object.entries(t.shadow).map(([k, x]) => [`shadow-${k}`, v(x)]);
const motion = [
  ...Object.entries(t.motion.duration).map(([k, x]) => [`motion-${k}`, v(x)]),
  ...Object.entries(t.motion.easing).map(([k, x]) => [`ease-${k}`, v(x)]),
];

const theme = (c) =>
  [
    ["bg", c.background],
    ["surface-1", c.surface1],
    ["surface-2", c.surface2],
    ["surface-3", c.surface3],
    ["surface-hover", c.surfaceHover],
    ["border", c.border],
    ["border-subtle", c.borderSubtle],
    ["text", c.textPrimary],
    ["text-2", c.textSecondary],
    ["text-3", c.textMuted],
    ["disabled", c.textDisabled],
    ["accent", c.accent],
  ].map(([k, x]) => [k, v(x)]);

const dark = lines(theme(t.color.dark)).join("\n");
const light = lines(theme(t.color.light)).join("\n");

const css = `/* Generated by scripts/design-tokens.mjs from
   docs/brand/KeyJutsu-Design-Kit/design-tokens.json (${t.meta.name} ${t.meta.version}).
   Do not edit: change the kit and run \`pnpm tokens\`. */

:root {
${lines([...brand, ...semantic, ...state, ...risk, ...type, ...space, ...radius, ...control, ...layout, ...shadow, ...motion]).join("\n")}
}

/* Light by default; the system theme or an explicit data-theme overrides. */
:root,
[data-theme="light"] {
  color-scheme: light;
${light}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${dark.replaceAll("\n  ", "\n    ").replace(/^  /, "    ")}
  }
}

[data-theme="dark"] {
  color-scheme: dark;
${dark}
}
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    // Missing counts as stale.
  }
  if (current !== css) {
    console.error("apps/desktop/src/tokens.css is stale; run `pnpm tokens`.");
    process.exit(1);
  }
  console.log("tokens.css matches the design kit");
} else {
  writeFileSync(target, css);
  console.log(`wrote tokens.css from ${t.meta.name} ${t.meta.version}`);
}
