// Writes the entry points that re-export the types ts-rs generates from the
// Rust IPC types. With --check it only reports whether they are stale, which
// is how CI catches a Rust type added without its TypeScript counterpart.
//
// ts-rs names each file after the type, in one directory per crate folder. Two
// Rust types with the same name exported to the same folder overwrite each
// other silently, and which one survives depends on test order. That happened
// once (the plan crate's `Check` replaced the readiness `Check`), so crates
// export to folders of their own: types directly in generated/ are re-exported
// by name from index.ts, and each subfolder becomes a namespace, e.g. `plan`.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const src = join(dirname(fileURLToPath(import.meta.url)), "..", "src");
const generated = join(src, "generated");
const header = [
  "// Generated by scripts/write-index.mjs from the files ts-rs writes during",
  "// `cargo test`. Do not edit by hand; run `pnpm types:index`.",
];

const typesIn = (dir) =>
  readdirSync(dir)
    .filter((f) => f.endsWith(".ts"))
    .map((f) => f.slice(0, -3))
    .sort();

const folders = readdirSync(generated)
  .filter((f) => statSync(join(generated, f)).isDirectory())
  .sort();

const outputs = new Map();
const rootTypes = typesIn(generated);
outputs.set(
  join(src, "index.ts"),
  [
    ...header,
    ...rootTypes.map((n) => `export type { ${n} } from "./generated/${n}";`),
    ...folders.map((f) => `export type * as ${f} from "./${f}";`),
    "",
  ].join("\n"),
);
let count = rootTypes.length;
for (const folder of folders) {
  const names = typesIn(join(generated, folder));
  count += names.length;
  outputs.set(
    join(src, `${folder}.ts`),
    [
      ...header,
      ...names.map((n) => `export type { ${n} } from "./generated/${folder}/${n}";`),
      "",
    ].join("\n"),
  );
}

const check = process.argv.includes("--check");
let stale = false;
for (const [path, content] of outputs) {
  if (check) {
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch {
      // Missing counts as stale.
    }
    if (current !== content) {
      console.error(`${path} is stale; run \`pnpm types:index\`.`);
      stale = true;
    }
  } else {
    writeFileSync(path, content);
  }
}
if (stale) process.exit(1);
const where = folders.length ? ` (namespaces: ${folders.join(", ")})` : "";
console.log(
  `${check ? "entry points re-export" : "wrote entry points for"} ${count} types${where}`,
);
