// Writes src/index.ts, re-exporting every type ts-rs generated from the Rust
// IPC types. With --check it only reports whether the index is stale, which
// is how CI catches a Rust type added without its TypeScript counterpart.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "src");
const names = readdirSync(join(root, "generated"))
  .filter((f) => f.endsWith(".ts"))
  .map((f) => f.slice(0, -3))
  .sort();

const content = [
  "// Generated by scripts/write-index.mjs from the files ts-rs writes during",
  "// `cargo test`. Do not edit by hand; run `pnpm types:index`.",
  ...names.map((n) => `export type { ${n} } from "./generated/${n}";`),
  "",
].join("\n");

const target = join(root, "index.ts");
if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    // Missing counts as stale.
  }
  if (current !== content) {
    console.error("packages/types/src/index.ts is stale; run `pnpm types:index`.");
    process.exit(1);
  }
  console.log(`index.ts re-exports all ${names.length} generated types`);
} else {
  writeFileSync(target, content);
  console.log(`wrote index.ts with ${names.length} types`);
}
