//! Messages between the desktop window and the core.
//!
//! These live here rather than in the desktop crate so their TypeScript
//! bindings are generated by the core's tests, before any frontend exists to
//! build the desktop crate against.

use serde::{Deserialize, Serialize};

use crate::session::SessionEvent;
use keyjutsu_terminal::{ProfileMode, ShellKind, TerminalSize};

/// What streams from a session to its terminal view.
#[derive(Debug, Clone, Serialize, ts_rs::TS)]
#[serde(tag = "kind", rename_all = "snake_case")]
#[ts(export)]
pub enum TerminalMessage {
    Output { data: String },
    Event { event: SessionEvent },
}

/// The parts of a session the window may choose. Everything else, such as
/// who answers cursor queries and which keys disarm, is decided by the core.
#[derive(Debug, Clone, Deserialize, ts_rs::TS)]
#[ts(export)]
pub struct OpenRequest {
    pub shell: ShellKind,
    pub profile: ProfileMode,
    pub size: TerminalSize,
}

/// Where a performance's commands come from. The window names a source; it
/// does not send a script for the built-in demo.
#[derive(Debug, Clone, Deserialize, ts_rs::TS)]
#[serde(tag = "kind", rename_all = "snake_case")]
#[ts(export)]
pub enum ScriptSource {
    SafeDemo,
    /// Commands the operator typed into the workspace. Until approved plan
    /// snapshots exist they carry no approval and run exactly as if typed.
    OperatorCommands {
        commands: Vec<String>,
    },
}
