//! Messages between the desktop window and the core.
//!
//! These live here rather than in the desktop crate so their TypeScript
//! bindings are generated by the core's tests, before any frontend exists to
//! build the desktop crate against.

use serde::{Deserialize, Serialize};

use crate::session::SessionEvent;
use keyjutsu_terminal::{ProfileMode, ShellKind, TerminalSize};

/// What streams from a session to its terminal view.
#[derive(Debug, Clone, Serialize, ts_rs::TS)]
#[serde(tag = "kind", rename_all = "snake_case")]
#[ts(export)]
pub enum TerminalMessage {
    Output { data: String },
    Event { event: SessionEvent },
}

/// The parts of a session the window may choose. Everything else, such as
/// who answers cursor queries and which keys disarm, is decided by the core.
#[derive(Debug, Clone, Deserialize, ts_rs::TS)]
#[ts(export)]
pub struct OpenRequest {
    pub shell: ShellKind,
    pub profile: ProfileMode,
    pub size: TerminalSize,
}

/// Where a performance's commands come from. The window names a source; it
/// does not send a script for the built-in demo.
#[derive(Debug, Clone, Deserialize, ts_rs::TS)]
#[serde(tag = "kind", rename_all = "snake_case")]
#[ts(export)]
pub enum ScriptSource {
    SafeDemo,
    /// Commands the operator typed into the workspace. Until approved plan
    /// snapshots exist they carry no approval and run exactly as if typed.
    OperatorCommands {
        commands: Vec<String>,
    },
}

/// What streams from a plan run to the window.
#[derive(Debug, Clone, Serialize, ts_rs::TS)]
#[serde(tag = "kind", rename_all = "snake_case")]
#[ts(export)]
pub enum RunMessage {
    Execution {
        event: crate::execute::ExecutionEvent,
    },
    /// A critical step is next: the window asks for the phrase and answers
    /// with `plan_confirm`. Nothing runs until it does.
    Confirm {
        confirmation: crate::execute::CriticalConfirmation,
    },
    /// Resuming after a session boundary: what KeyJutsu checked. The window
    /// asks the operator and answers with `plan_confirm`, `RESUME` to go on.
    /// Nothing more runs until it does.
    Resume {
        notice: crate::boundary::BoundaryNotice,
    },
    Done {
        outcome: crate::execute::Outcome,
        snapshot: String,
        checkpoint: String,
        /// What the run did to each Git repository it worked in.
        git: Vec<crate::git::RepoReport>,
        /// The id it was recorded under in the encrypted history, if it was.
        #[ts(optional)]
        session: Option<String>,
    },
}

/// A sealed snapshot, as the window is told about it.
#[derive(Debug, Clone, Serialize, ts_rs::TS)]
#[ts(export)]
pub struct Sealed {
    pub snapshot_hash: String,
    /// Where it was written, so the CLI can run or recover it too.
    pub path: String,
    pub sealed_at: String,
}

/// A run that stopped at a session boundary and has not crossed it yet.
#[derive(Debug, Clone, Serialize, ts_rs::TS)]
#[ts(export)]
pub struct WaitingRun {
    pub title: String,
    pub after_phase: String,
    pub boundary: keyjutsu_plan::model::Boundary,
    pub recorded_at: String,
}

/// A waiting run, opened to continue: the plan to show, and its snapshot.
#[derive(Debug, Clone, Serialize, ts_rs::TS)]
#[ts(export)]
pub struct WaitingOpened {
    pub view: crate::workspace::WorkspaceView,
    pub sealed: Sealed,
}

/// A Technique made into a draft plan in the workspace, and how this machine
/// compares with where it worked. Nothing is approved or run: the draft is
/// validated and approved like any other plan.
#[derive(Debug, Clone, Serialize, ts_rs::TS)]
#[ts(export)]
pub struct TechniqueDraft {
    pub view: crate::workspace::WorkspaceView,
    pub fit: crate::technique::Fit,
}
